#.travis.yml

sudo: required

dist: trusty

language: node_js

node_js:
  - 8

before_deploy:
  - ssh-agent -k

env:
  global:
  - DBUS_SESSION_BUS_ADDRESS=/dev/null
  - CHROME_BIN=chromium-browser
  - TRAVIS=true

before_script:
  - set -e
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ng build bugsplat-ng

install:
  - npm install

script:
  - npm run test "bugsplat-ng" -- --watch=false --progress=false
  - npm run test "my-angular6-crasher" -- --watch=false --progress=false